name: Execute_test_on_push
permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Party.Echo.Execute/**'
      - '.github/workflows/Execute*.yml'
  workflow_dispatch:

jobs:
  work_push:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/official_task_pipeline.yml@main
    with:
      workflow_mode: work
      os: all
      workdir: Party.Echo.Execute
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      target_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_vars: |
        {
          "USERNAME": ${{ toJSON(secrets.USERNAME) }},
          "PASSWORD": ${{ toJSON(secrets.PASSWORD) }}
        }
