#USE THIS WORKFLOW ONLY WHEN YOU WANT TO RELEASE MANUALLY WITHOUT TESTS
name: Execute quick release
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  main_release:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/official_task_pipeline.yml@main
    with:
      workflow_mode: release
      os: all
      workdir: Party.Echo.Execute
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      target_feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}
      env_vars: |
          {
            "FOO": ${{ toJSON(secrets.FOO) }},
            "BAR": ${{ toJSON(secrets.BAR) }}
          }
