name: Execute_test_on_main

on:
  push:
    branches:
      - main
    paths:
      - 'Party.Echo.Execute/**'
      - '.github/workflows/Execute*.yml'
  workflow_dispatch:

jobs:
  main_test:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/official_task_pipeline.yml@main
    with:
      workflow_mode: main
      os: all
      workdir: Party.Echo.Execute
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_vars: |
        {
          "FOO": ${{ toJSON(secrets.FOO) }},
          "BAR": ${{ toJSON(secrets.BAR) }}
        }
