name: .NET Setup & Restore
description: Checkout, setup .NET SDK, and restore dependencies

inputs:
  dotnet-version:
    required: false
    default: '8.0.x'
    description: 'The .NET SDK version to use'

  working-directory:
    required: false
    type: string
    default: '.'
    description: 'Working directory for the build, relative to repository root, e.g. Frends.Common.Toolkit'

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5.2.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: dotnet restore
