name: Common Toolkit Release

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.Common.Toolkit/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/toolkit/toolkit_release.yml@main
    with:
      working_directory: 'Frends.Common.Toolkit'
      project_directory: 'Frends.Common.Toolkit'
