name: Pack .NET project
description: Setup .NET SDK, restore dependencies, build and pack a .NET project with one step

inputs:
  dotnet-version:
    required: false
    default: '8.0.x'
    description: 'The .NET SDK version to use'

  working-directory:
    required: false
    default: '.'
    description: 'Working directory for the build, relative to repository root, e.g. Frends.Common.Toolkit'

runs:
  using: composite

  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5.2.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: dotnet restore

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: dotnet build --no-restore --configuration Release

    - name: Pack
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: dotnet pack --no-restore --no-build --configuration Release
