name: Analyzers Release

on:
  push:
    branches:
      # TODO: Replace branch with main
      - fspw-281
    paths:
      - 'FrendsTaskAnalyzers/**'
  workflow_dispatch:

env:
  DOTNET_NOLOGO: 'true'
  DOTNET_VERSION: '9.0.x'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      tag: ${{ steps.get-version.outputs.tag }}
    defaults:
      run:
        working-directory: 'FrendsTaskAnalyzers/'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - id: get-version
        name: Get project version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" FrendsTaskAnalyzers/FrendsTaskAnalyzers.csproj || echo "1.0.0")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          # TODO: Remove suffix
          echo "tag=v$VERSION-fspw281" >> $GITHUB_OUTPUT

      - id: check-tag
        name: Check if the tag exists
        run: |
          if git rev-parse "refs/tags/${{ steps.get-version.outputs.tag }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - if: ${{ steps.check-tag.outputs.exists == 'true' }}
        run: |
          echo "Duplicate tag found"
          exit 1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: 'FrendsTaskAnalyzers/**/*.csproj'

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Pack
        run: dotnet pack --no-build --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: 'release'
          path: |
            FrendsTaskAnalyzers/FrendsTaskAnalyzers/bin/${{ env.BUILD_CONFIGURATION }}/**/*.dll
            FrendsTaskAnalyzers/FrendsTaskAnalyzers/bin/${{ env.BUILD_CONFIGURATION }}/**/*.nupkg
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: 'release'

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          # TODO: Remove after testing
          draft: true
          files: |
            **/*.dll
            **/*.nupkg
          name: FrendsTaskAnalyzers v${{ needs.build.outputs.version }}
          tag_name: ${{ needs.build.outputs.tag }}
          fail_on_unmatched_files: true
