name: Common Toolkit Test

on:
  push:
    branches:
      - '**'
    paths:
      - 'Frends.Common.Toolkit/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/toolkit_test.yml@main
    with:
      working-directory: 'Frends.Common.Toolkit'
      project-directory: 'Frends.Common.Toolkit'
