name: Common Toolkit Release

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.Common.Toolkit/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/toolkit_release.yml@fspw-732-CommonLib-PoC
    with:
      working-directory: 'Frends.Common.Toolkit'
      project-directory: 'Frends.Common.Toolkit'
