name: linux_build_test.yml

on:
  workflow_call:
    inputs:
      env_var_name_1:
        required: false
        type: string
      env_var_name_2:
        required: false
        type: string
      env_var_name_3:
        required: false
        type: string
      env_var_name_4:
        required: false
        type: string
      env_var_name_5:
        required: false
        type: string
      env_var_name_6:
        required: false
        type: string
      env_var_name_7:
        required: false
        type: string
      env_var_name_8:
        required: false
        type: string
      workdir:
        required: false
        type: string
      prebuild_command:
        required: false
        type: string
    secrets:
      env_var_value_1:
        required: false
      env_var_value_2:
        required: false
      env_var_value_3:
        required: false
      env_var_value_4:
        required: false
      env_var_value_5:
        required: false
      env_var_value_6:
        required: false
      env_var_value_7:
        required: false
      env_var_value_8:
        required: false
      badge_service_api_key:
        required: true
      test_feed_api_key:
        required: true
      build_time_nuget_feed_url:
        required: false
      build_time_nuget_feed_api_key:
        required: false

env:
  azure_artifacts_feed_url: https://pkgs.dev.azure.com/frends-platform/frends-tasks/_packaging/test/nuget/v3/index.json

jobs:
  CodeQualityCheck:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0
    
    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: main
        OUTPUT_DETAILS: detailed
        VALIDATE_CSHARP: true
        IGNORE_GITIGNORED_FILES: true
        FILTER_REGEX_INCLUDE: "${{ inputs.workdir }}/"

  Analyze:
    name: Code Security Check
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Set working directory if provided
      if: ${{ inputs.workdir != '' }}
      run: |
        echo "workdir=${{ inputs.workdir }}" >> $GITHUB_ENV

    - name: Set working directory to default if not provided
      if: ${{ inputs.workdir == '' }}
      run: |
        echo "workdir=." >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      continue-on-error: true

    - name: Analyze
      uses: github/codeql-action/analyze@v2

    - name: Print Sarif To Summary 
      run: |
        report=$(find . -name "results.sarif")
        while IFS= read -r line
        do
          echo "$line" >> $GITHUB_STEP_SUMMARY
        done < "$input"

  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    ###############################
    # SETUP DOTNET                #
    ###############################
    # When setting up dotnet, we need to check if a custom nuget feed is used
    # However in GitHub Actions, in 'if' statements we cannot refer to 'secret' values, thus
    # we need to use a small script to check if the secret is defined or not and then set an
    # output to either true or false.
    - name: Check for custom feed URL
      id: check_for_build_time_feed
      shell: pwsh
      run: |
        if ("${{ secrets.build_time_nuget_feed_url }}" -eq "")
        { "Custom feed URL missing"; echo "build_time_nuget_feed_defined=false" >> $env:GITHUB_OUTPUT }
        else 
        { "Custom feed URL present"; echo "build_time_nuget_feed_defined=true" >> $env:GITHUB_OUTPUT }

    - uses: actions/setup-dotnet@v1
      name: Setup dotnet (no custom feed)
      if: ${{ steps.check_for_build_time_feed.outputs.build_time_nuget_feed_defined == 'false' }}
      with:
        dotnet-version: '6.0.x'
    
    # If a custom nuget feed is used, we need to add it when setting up dotnet
    - uses: actions/setup-dotnet@v1
      name: Setup dotnet (with custom feed)
      if: ${{ steps.check_for_build_time_feed.outputs.build_time_nuget_feed_defined == 'true' }}
      with:
        dotnet-version: '6.0.x'
        source-url: ${{ secrets.build_time_nuget_feed_url }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.build_time_nuget_feed_api_key }} 

    ###############################
    # SETUP ENVIRONMENT IF NEEDED #
    ###############################
    - name: Set env var 1
      if: ${{ inputs.env_var_name_1 != '' }}
      run: |
        echo "::add-mask::${{ secrets.env_var_value_1 }}"
        echo "${{ inputs.env_var_name_1 }}=${{ secrets.env_var_value_1 }}" >> $GITHUB_ENV
        
    - name: Set env var 2
      if: ${{ inputs.env_var_name_2 != '' }}
      run: |
        echo "::add-mask::${{ secrets.env_var_value_2 }}"
        echo "${{ inputs.env_var_name_2 }}=${{ secrets.env_var_value_2 }}" >> $GITHUB_ENV
        
    - name: Set env var 3
      if: ${{ inputs.env_var_name_3 != '' }}
      run: |
        echo "::add-mask::${{ secrets.env_var_value_3 }}"
        echo "${{ inputs.env_var_name_3 }}=${{ secrets.env_var_value_3 }}" >> $GITHUB_ENV
        
    - name: Set env var 4
      if: ${{ inputs.env_var_name_4 != '' }}
      run: |
        echo "::add-mask::${{ secrets.env_var_value_4 }}"
        echo "${{ inputs.env_var_name_4 }}=${{ secrets.env_var_value_4 }}" >> $GITHUB_ENV

    - name: Set env var 5
      if: ${{ inputs.env_var_name_5 != '' }}
      run: |
        echo "::add-mask::${{ secrets.env_var_value_5 }}"
        echo "${{ inputs.env_var_name_5 }}=${{ secrets.env_var_value_5 }}" >> $GITHUB_ENV

    - name: Set env var 6
      if: ${{ inputs.env_var_name_6 != '' }}
      run: |
        echo "::add-mask::${{ secrets.env_var_value_6 }}"
        echo "${{ inputs.env_var_name_6 }}=${{ secrets.env_var_value_6 }}" >> $GITHUB_ENV

    - name: Set env var 7
      if: ${{ inputs.env_var_name_7 != '' }}
      run: |
        echo "::add-mask::${{ secrets.env_var_value_7 }}"
        echo "${{ inputs.env_var_name_7 }}=${{ secrets.env_var_value_7 }}" >> $GITHUB_ENV

    - name: Set env var 8
      if: ${{ inputs.env_var_name_8 != '' }}
      run: |
        echo "::add-mask::${{ secrets.env_var_value_8 }}"
        echo "${{ inputs.env_var_name_8 }}=${{ secrets.env_var_value_8 }}" >> $GITHUB_ENV

    - name: Set working directory if provided
      if: ${{ inputs.workdir != '' }}
      run: |
        echo "workdir=${{ inputs.workdir }}" >> $GITHUB_ENV

    - name: Set working directory to default if not provided
      if: ${{ inputs.workdir == '' }}
      run: |
        echo "workdir=." >> $GITHUB_ENV

    ###############################
    # Install required tools      #
    ###############################
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install xmlstarlet -y
        
    ###############################
    # Run prebuild command        #
    ###############################
    - name: Run prebuild command
      if: ${{ inputs.prebuild_command != '' }}
      run: ${{ inputs.prebuild_command }}
      working-directory: "${{ env.workdir }}"

    ###############################
    # Build, test, report results #
    ###############################
    - name: Build
      run: dotnet build
      working-directory: "${{ env.workdir }}"
    
    - name: Test
      run: |
        dotnet test --collect:"XPlat Code Coverage"
      working-directory: "${{ env.workdir }}"

    - name: Check Code Coverage
      id: get_line_rate
      run: |
        report=$(find . -name "coverage.cobertura.xml")
        cp $report .
        coverage=$(xmlstarlet sel -t -v '//coverage/@line-rate' coverage.cobertura.xml)
        covPercent=$(echo "$coverage * 100" | bc -l)
        coverageInt=$(printf "%.0f" $covPercent)
        if test $coverageInt -lt 80 
        then
          echo "Test coverage $coverageInt% was not in the tolerance 80%"
          echo "The Code Check failed! :x:" >> $GITHUB_STEP_SUMMARY
          echo "## Test coverage $coverageInt% was not in the tolerance 80% :thumbsdown:" >> $GITHUB_STEP_SUMMARY
          exit 1
        else
          echo "The Code Check passed :raised_hands:" >> $GITHUB_STEP_SUMMARY
          echo "## Test coverage $coverageInt% :thumbsup:" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Pack release version of task
      run: dotnet pack --configuration Release --include-source
      working-directory: "${{ env.workdir }}"
      
    - name: Save coverage results
      id: vars
      run: |
        badgeKey="${{ github.repository }}|${{ github.ref_name }}"
        apiKey="${{ secrets.badge_service_api_key }}"
        if [ "${{ env.workdir }}" != '.' ]; then
          badgeKey="${{ github.repository }}/${{ env.workdir }}|${{ github.ref_name }}"
        fi
        coverageReport=$(find . -name "coverage.cobertura.xml")
        mv $coverageReport .
        coverage=$(xmlstarlet sel -t -v '//coverage/@line-rate' coverage.cobertura.xml)
        covPercent=$(echo "$coverage * 100" | bc -l)
        coverageInt=$(printf "%.0f" $covPercent)
        json="{\"key\":\"$badgeKey\",\"displayName\":\"Coverage\",\"value\":\"$coverageInt%\"}"
        curl -X POST -H "x-api-key: $apiKey" -H "Content-Type: application/json" -d $json https://app-github-custom-badges.azurewebsites.net/Badge
      working-directory: "${{ env.workdir }}"


    # Setup dotnet again with test feed
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        source-url: ${{ env.azure_artifacts_feed_url }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.test_feed_api_key }}
    # Push the package to the test feed
    - name: Push NuGet package(s) to the test feed
      run: dotnet nuget push "**/*.nupkg"  --api-key ${{ secrets.test_feed_api_key }} --source ${{ env.azure_artifacts_feed_url }} --skip-duplicate
      working-directory: "${{ env.workdir }}"
