name: Release Toolkit Template
permissions:
  contents: read

on:
  push:
    paths:
      - 'FrendsToolkitTemplate/**'
      - '.github/workflows/*toolkit*.yml'

env:
  azure_artifacts_feed_url: ${{ github.ref_name == 'main' && 'https://pkgs.dev.azure.com/frends-platform/frends-tasks/_packaging/main/nuget/v3/index.json' || 'https://pkgs.dev.azure.com/frends-platform/frends-tasks/_packaging/test/nuget/v3/index.json' }}
  nuget_api_key: ${{ github.ref_name == 'main' && secrets.TASKS_FEED_API_KEY || secrets.TASKS_TEST_FEED_API_KEY }}
  skip_duplicate: ${{ github.ref_name != 'main' }}
  working_directory: FrendsToolkitTemplate
  dotnet-version: '8.0.x'

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup
        uses: ./.github/actions/dotnet-pack
        with:
          dotnet-version: ${{ env.dotnet-version }}
          working-directory: ${{ env.working_directory }}

      - name: Test
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage"
        working-directory: '${{ env.working_directory }}/Template/Company.Echo.Toolkit'

      - name: Test coverage
        id: code_coverage
        uses: ./.github/actions/check-coverage
        with:
          repository: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          badge-key-scope: ${{ env.working_directory }}
          badge-service-api-key: ${{ secrets.BADGE_SERVICE_API_KEY }}

      - name: Push NuGet package(s)
        env:
          NUGET_AUTH_TOKEN: ${{ env.nuget_api_key }}
        run: |
          ARGS="--api-key ${{ env.nuget_api_key }} --source ${{ env.azure_artifacts_feed_url }}"
          if [ "${{ env.skip_duplicate }}" = "true" ]; then
            ARGS="$ARGS --skip-duplicate"
          fi
          dotnet nuget push ${{ env.working_directory }}/bin/Release/frends-toolkit.*.nupkg $ARGS
