name: Toolkit Test

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
        description: 'Working directory for the build, relative to repository root, e.g. Frends.Common.Toolkit'
      project-directory:
        required: true
        type: string
        description: 'Directory of the project to build, relative to working directory, e.g. Frends.Common.Toolkit (so from root it would be Frends.Common.Toolkit/Frends.Common.Toolkit)'
      dotnet-version:
        required: false
        type: string
        default: '8.0.x'
        description: 'Version of .NET SDK to use, e.g. 6.0.x, 8.0.x'
      min-coverage:
        required: false
        type: number
        default: 80
        description: 'Minimum required line coverage percentage'

permissions:
  contents: read

jobs:
  Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  ${{ inputs.working-directory }}
    steps:
      - name: Setup
        uses: FrendsPlatform/FrendsTasks/.github/actions/dotnet-setup@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Lint
        run: dotnet format --no-restore --verify-no-changes

  Build:
    needs: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Setup
        uses: FrendsPlatform/FrendsTasks/.github/actions/dotnet-setup@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Pack
        run: dotnet pack --no-restore --no-build --configuration Release

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: nuget-packages
          path: '${{ inputs.project-directory }}/bin/Release/*.nupkg'
          retention-days: 7

  Test:
    needs: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Setup
        uses: FrendsPlatform/FrendsTasks/.github/actions/dotnet-setup@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          working-directory: ${{ inputs.working-directory }}

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Test coverage
        id: code_coverage
        uses: FrendsPlatform/FrendsTasks/.github/actions/check-coverage@main
        with:
          min-line-coverage: ${{ inputs.min-coverage }}
          repository: ${{ github.repository }}
          branch: ${{ github.ref_name }}
          badge-key-scope: ${{ inputs.project-directory }}
          badge-service-api-key: ${{ secrets.BADGE_SERVICE_API_KEY }}


